services:

  postgresqldb:
    image: postgres
    volumes:
      - ${PWD}/postgres-data:/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=testdb
